
# Full list of variables used for workforce manipulation

# Occupation codes -------------------------------------------------------------
nurse_codes <- function() {
  nurse_staff_codes <<- c("N0A", "N0B", "N0C", "N0D", "N0E", "N0F", "N0G", "N0H", "N0J", "N0K", "N0L",
                          "N1B", "N1C", "N1H", "N1J", "N1L", "N4D", "N4F", "N4H", "N5D", "N5F", "N5H",
                          "N6A", "N6B", "N6C", "N6D", "N6E", "N6F", "N6G", "N6H", "N6J", "N6K", "N6L",
                          "N7A", "N7B", "N7C", "N7D", "N7E", "N7F", "N7G", "N7H", "N7K", "N7L", "NAA",
                          "NAB", "NAC", "NAD", "NAE", "NAF", "NAG", "NAH", "NAJ", "NAK", "NAL", "NBK",
                          "NCA", "NCB", "NCC", "NCD", "NCE", "NCF", "NCG", "NCH", "NCJ", "NCK", "NCL",
                          "NEH", "P2B", "P2E", "P2C", "P2D", "P3C", "P3D", "P3E", "N7J", "N1A", "NNN", 'P2A', 'P3A')
  
  nursing_associate_codes <<- c('NGA', 'NGB', 'NGC', 'NGD', 'NGE', 'NGF', 'NGG', 'NGH',
                                'NFA', 'NFB', 'NFC', 'NFD', 'NFE', 'NFF', 'NFG', 'NFH', 'NFJ', 'NFK', 'NFL',
                                'NHA', 'NHB', 'NHC', 'NHD', 'NHE', 'NHF', 'NHG', 'NHH',
                                'N8A', 'N8B', 'N8C', 'N8D', 'N8E', 'N8F', 'N8G', 'N8H', 'N8K', 'N8L',
                                'N9A', 'N9B', 'N9C', 'N9D', 'N9E', 'N9F', 'N9G', 'N9H', 'N9J', 'N9K', 'N9L')
}


occ_codes <- function() {
  ambulance_staff_codes <<- c('A4A', 'A4B', 'A4C','A4D',
                              'A0A', 'A0B', 'A0D',
                              'A5A', 'A5B', 'A5C', 'A5D', 'A5E',
                              'A6A', 'A6B', 'A6C', 'A6D', 'A6E',
                              'ABA', 'ABB', 'ABC', 'ABD', 'ABE')
  
  support_ambulance_staff_codes <<-  c('AEA', 'AEB', 'AEC', 'AED', 'AEE',
                                       'A7A', 'A7B', 'A7C',
                                       'A8A', 'A8B', 'A8C', 'A8E',
                                       'A9C')
  
  admin_and_estates_codes <<- c('G0A', 'G0B', 'G0C', 'G0D', 'G0E',
                                'G1A', 'G1B', 'G1C', 'G1D', 'G1E',
                                'G2A', 'G2B', 'G2C', 'G2D', 'G2E',
                                'G3B', 'G3C', 'G3D', 'G3E')
  
  hca_and_support_codes <<- c('H1A', 'H1B', 'H1C', 'H1D', 'H1E', 'H1F', 'H1G', 'H1H',
                              'H1J', 'H1K', 'H1L', 'H1M', 'H1N', 'H1P', 'H1R',
                              'H2A', 'H2B', 'H2C', 'H2D', 'H2E', 'H2F', 'H2G', 'H2H',
                              'H2J', 'H2K', 'H2L', 'H2M', 'H2N', 'H2P', 'H2R')
  
  medical_hospital_codes <<- c(001,002,003,004,005,006,007,008,
                               010,011,012,013,014,015,016,017,018,
                               020,021,022,023,024,025,026,027,028,
                               030,031,032,033,034,035,036,037,
                               040,041,045,046,047,048,
                               051,052,053,054,056,
                               061,062,063,064,065,066,067,068,
                               070,071,072,073,074,075,077,078,
                               080,084,085,086,087,088,
                               090,091,092,093,094,095,096,097)
  
  medical_gp_codes <<- c(800,
                         920,921,
                         930,
                         970,971,976,977,978,979,
                         980,
                         996)
  
  nurse_staff_codes <<- c("N0A", "N0B", "N0C", "N0D", "N0E", "N0F", "N0G", "N0H", "N0J", "N0K", "N0L",
                          "N1B", "N1C", "N1H", "N1J", "N1L", "N4D", "N4F", "N4H", "N5D", "N5F", "N5H",
                          "N6A", "N6B", "N6C", "N6D", "N6E", "N6F", "N6G", "N6H", "N6J", "N6K", "N6L",
                          "N7A", "N7B", "N7C", "N7D", "N7E", "N7F", "N7G", "N7H", "N7K", "N7L", "NAA",
                          "NAB", "NAC", "NAD", "NAE", "NAF", "NAG", "NAH", "NAJ", "NAK", "NAL", "NBK",
                          "NCA", "NCB", "NCC", "NCD", "NCE", "NCF", "NCG", "NCH", "NCJ", "NCK", "NCL",
                          "NEH", "P2B", "P2E", "P2C", "P2D", "P3C", "P3D", "P3E", "N7J", "N1A", "NNN", 'P2A', 'P3A')
  
  nursing_associate_codes <<- c('NGA', 'NGB', 'NGC', 'NGD', 'NGE', 'NGF', 'NGG', 'NGH',
                                'NFA', 'NFB', 'NFC', 'NFD', 'NFE', 'NFF', 'NFG', 'NFH', 'NFJ', 'NFK', 'NFL',
                                'NHA', 'NHB', 'NHC', 'NHD', 'NHE', 'NHF', 'NHG', 'NHH',
                                'N8A', 'N8B', 'N8C', 'N8D', 'N8E', 'N8F', 'N8G', 'N8H', 'N8K', 'N8L',
                                'N9A', 'N9B', 'N9C', 'N9D', 'N9E', 'N9F', 'N9G', 'N9H', 'N9J', 'N9K', 'N9L')
  
  
  nurse_health_visitor_codes <<- c("N3H")
  
  midwife_staff_codes <<- c('N2C', 'N2J', 'N2L')
  
  
  allied_health_codes <<- c('SAA', 'SAB', 'SAC', 'SAD', 'SAE', 'SAF', 'SAG', 'SAH', 'SAI', 'SAJ',
                            'S0A', 'S0B', 'S0C', 'S0D', 'S0E', 'S0F', 'S0G', 'S0H', 'S0I', 'S0J', 'S0T', 'S0V',
                            'S1A', 'S1B', 'S1C', 'S1D', 'S1E', 'S1F', 'S1G', 'S1H', 'S1I', 'S1J', 'S1T', 'S1V',
                            'S2D',
                            'S4A', 'S4C', 'S4D', 'S4F', 'S4I',' S4T',
                            'S6C', 'S6E', 'S6H', 'S6J',
                            'S7A', 'S7C', 'S7D', 'S7E', 'S7F', 'S7J')
  
  support_allied_codes <<- c('S5A', 'S5B', 'S5C', 'S5D', 'S5E', 'S5F', 'S5G', 'S5H', 'S5I', 'S5J', 'S5T', 'S5V',
                             'S8A', 'S8B', 'S8C', 'S8D', 'S8E', 'S8F', 'S8G', 'S8H', 'S8I', 'S8J', 'S8T', 'S8V',
                             'S9A', 'S9B', 'S9C', 'S9D', 'S9E', 'S9F', 'S9G', 'S9H', 'S9I', 'S9J', 'S9T', 'S9V')
  
  
  other_scientific_staff_codes <<- c('SAK', 'SAL', 'SAM', 'SAP', 'SAR', 'SAX',
                                     'S0K', 'S0L', 'S0M', 'S0P', 'S0R', 'S0U', 'S0X',
                                     'S1K', 'S1L', 'S1M', 'S1R', 'S1U', 'S1X',
                                     'S2L', 'S2M', 'S2P', 'S2X',
                                     'S3L', 'S3P', 'S3X',
                                     'S4L', 'S4P', 'S4R', 'S4X',
                                     'S6K', 'S6U', 'S6U',
                                     'S7R', 'S7U', 'S7X')
  
  other_scientific_support_codes <<- c('S5K', 'S5L', 'S5M', 'S5P', 'S5R', 'S5U', 'S5X',
                                       'S8L', 'S8M', 'S8P', 'S8R', 'S8U', 'S8X',
                                       'S9K', 'S9L', 'S9P', 'S9R', 'S9U', 'S9X')
  
  
  life_science_codes <<- c('UAA', 'UAB', 'UAC', 'UAD',
                           'U0A', 'U0B', 'U0C', 'U0D',
                           'U1A', 'U1B', 'U1C', 'U1D',
                           'U2A', 'U2B', 'U2C', 'U2D',
                           'U3A', 'U3B', 'U3C', 'U3D',
                           'U4A', 'U4B', 'U4C', 'U4D')
  
  life_science_support <<- c('U5A', 'U5B', 'U5C', 'U5D',
                             'U6A', 'U6B', 'U6C', 'U6D',
                             'U7A', 'U7B', 'U7C', 'U7D',
                             'U8A', 'U8B', 'U8C', 'U8D',
                             'U9A', 'U9B', 'U9C', 'U9D')
  
  physiological_science_codes <<- c('UAE', 'UAF', 'UAG',
                                    'U0E', 'U0F', 'U0G',
                                    'U1E', 'U1F', 'U1G',
                                    'U2E', 'U2F', 'U2G',
                                    'U3E', 'U3F', 'U3G',
                                    'U4E', 'U4F', 'U4G' )
  
  physiological_science_support <<- c('U5E', 'U5F', 'U5G',
                                      'U6E', 'U6F', 'U6G',
                                      'U7E', 'U7F', 'U7G',
                                      'U8E', 'U8F', 'U8G',
                                      'U9E', 'U9F', 'U9G')
  
  
  physical_science_codes <<- c('UAH', 'UAJ', 
                               'U0H', 'U0J',
                               'U1H', 'U1J',
                               'U2H', 'U2J',
                               'U3H', 'U3J',
                               'U4H', 'U4J')
  
  physical_science_support <<- c('U5H', 'U5J', 
                                 'U6H', 'U6J',
                                 'U7H', 'U7J',
                                 'U8H', 'U8J',
                                 'U9H', 'U9J')
  
  clinical_science_codes <<- c('UAK', 
                               'U0K',
                               'U1K',
                               'U2K',
                               'U3K',
                               'U4K')
  
  clinical_science_support <<- c('U5K', 
                                 'U6K',
                                 'U7K',
                                 'U8K',
                                 'U9K')
  
  public_science_codes <<- c('UAL', 'UAM', 
                             'U0L', 'U0M',
                             'U1L', 'U1M',
                             'U2L', 'U2M',
                             'U3L', 'U3M',
                             'U4L', 'U4M')
  
  public_science_support <<- c('U5L', 'U5M', 
                               'U6L', 'U6M',
                               'U7L', 'U7M',
                               'U8L', 'U8M',
                               'U9L', 'U9M')
  
  
  general_payments_staff_codes <<- c('Z1A', 'Z1B', 'Z1C', 'Z1D', 'Z1E',
                                     'Z2E', 'Z2F')
  
  
}




####### ------------------------------------------------------------------------
other_functions <<- function() {
  uk_joiner_nqn <<- c("Immediate Joiner",
                      "1 Month",
                      "1 to 2 Months",
                      "2 to 3 Months",
                      "3 to 4 Months",
                      "4 to 5 Months",
                      "5 to 6 Months",
                      "6 to 7 Months",
                      "7 to 8 Months",
                      "8 to 9 Months",
                      "9 to 10 Months",
                      "10 to 11 Months",
                      "11 to 12 Months")
  
  occ_joiner_nqn <<- c("Immediate Joiner",
                       "1 Month",
                       "1 to 2 Months")
  
  domestic_trained <<- c("England",
                         "Northern Ireland",
                         "Scotland",
                         "Wales",
                         "UK")
}


# Org Codes --------------------------------------------------------------------

sector_org_codes <- function() {
  orgs_south_east_london <<- c("07Q",
                               "08A",
                               "TAK",
                               "5A7",
                               "5A8",
                               "RJ1",
                               "RJZ",
                               "5LD",
                               "RJ2",
                               "5LF",
                               "RRU",
                               "07N",
                               "07Q",
                               "08A",
                               "08K",
                               "08L",
                               "72Q",
                               "QKK",
                               "08Q",
                               "RPG",
                               "RV5",
                               "RYQ",
                               "5LE")
  
  orgs_north_east_london <<- c("5C2",
                               "RF4",
                               "RNJ",
                               "R1H",
                               "5C3",
                               "RWK",
                               "5A4",
                               "RQX",
                               "5C5",
                               "RNH",
                               "07L",
                               "07T",
                               "08F",
                               "08M",
                               "A3A8R",
                               "QMF",
                               "08N",
                               "08V",
                               "08W",
                               "RAT",
                               "5NA",
                               "5C4",
                               "5NC",
                               "RGC")
  
  orgs_north_central_london <<- c("RVL",
                                  "5A9",
                                  "RRP",
                                  "TAF",
                                  "5K7",
                                  "RV3",
                                  "5C1",
                                  "RP4",
                                  "5C9",
                                  "5K8",
                                  "RP6",
                                  "07M",
                                  "07R",
                                  "07X",
                                  "08D",
                                  "08H",
                                  "93C",
                                  "QMJ",
                                  "RAP",
                                  "RAL",
                                  "RNK",
                                  "RRV",
                                  "RKE")
  
  orgs_north_west_london <<- c("5K5",
                               "RYX",
                               "RQM",
                               "RC3",
                               "5HX",
                               "5H1",
                               "5K6",
                               "RAS2",
                               "5AT",
                               "5HY",
                               "RYJ",
                               "5LA",
                               "R1K",
                               "07P",
                               "09A",
                               "07W",
                               "08C",
                               "08E",
                               "08G",
                               "07Y",
                               "W2U3Z",
                               "QRV",
                               "08Y",
                               "RV8",
                               "RT3",
                               "RPY",
                               "RAN",
                               "RKL",
                               "RFW",
                               "5LC")
  
  orgs_south_west_london <<- c("RJ6",
                               "5K9",
                               "RVR",
                               "RY9",
                               "RAX",
                               "5A5",
                               "07V",
                               "08J",
                               "08R",
                               "08P",
                               "36L",
                               "QWE",
                               "08T",
                               "08X",
                               "5M6",
                               "RQY",
                               "RJ7",
                               "5M7",
                               "5LG")
  
  
  
  orgs_devon <<- c("RWV",
                   "5QQ",
                   "RX5",
                   "15N",
                   "QJK",
                   "99P",
                   "99Q",
                   "RBZ",
                   "5F1",
                   "RH8",
                   "RYF",
                   "RA9",
                   "R1G",
                   "TAL",
                   "RK9")
  
  
  orgs_bath_somerset_swindon_and_wiltshire <<- c("RVN",
                                                 "5FL",
                                                 "RN3",
                                                 "11E",
                                                 "92G",
                                                 "QOX",
                                                 "12D",
                                                 "99N",
                                                 "RBB",
                                                 "RD1",
                                                 "RNZ",
                                                 "5K3",
                                                 "5QK")
  
  orgs_gloucestershire <<- c('R1J',
                             'RTQ',
                             'RTE',
                             '5QH',
                             '11M',
                             'QR1')
  
  
  orgs_somerset <<- c('11X',
                      'QSL',
                      'RH5',
                      '5QL',
                      'RBA',
                      'RA4')
  
  orgs_cornwall_and_isles_of_scilly <<- c('5QP',
                                          'RJ8',
                                          'QT6',
                                          '11N',
                                          'REF')
  
  orgs_bristol_north_somerset_and_south_gloucestershire <<- c('5QJ',
                                                              '11H',
                                                              '15C',
                                                              'QUY',
                                                              '11T',
                                                              '12A',
                                                              'RVJ',
                                                              '5M8',
                                                              '5A3',
                                                              'RA7',
                                                              'RA3')
  
  orgs_dorset <<- c('5QN',
                    'RBD',
                    'RDY',
                    '5QM',
                    '11J',
                    'QVV',
                    'RD3',
                    'RDZ',
                    'R0D')
  
  
  
  
  orgs_kent_and_medway <<- c('RN7',
                             'RVV',
                             '5QA',
                             'RXY',
                             'RYY',
                             'RWF',
                             'RPA',
                             '5L3',
                             '09C',
                             '09E',
                             '09J',
                             '91Q',
                             'QKS',
                             '09W',
                             '10A',
                             '10D',
                             '10E',
                             '99J',
                             '5P9')
  
  orgs_frimley <<- c('5QG',
                     'RWX',
                     'RDU',
                     'RD7',
                     '10G',
                     '15D',
                     'D4U1Y',
                     'QNQ',
                     '99M',
                     '10T',
                     '10C',
                     '11C')
  
  orgs_sussex <<- c('5LQ',
                    'RXH',
                    '5P7',
                    'RXC',
                    '5P8',
                    '09D',
                    '09G',
                    '09H',
                    '09L',
                    '97R',
                    '09F',
                    '09P',
                    '99K',
                    '09X',
                    'QNX',
                    '70F',
                    'RPC',
                    'RYD',
                    'RDR',
                    'RX2',
                    'RYR',
                    '5P6')
  
  orgs_hampshire_and_isle_of_wight <<- c('RN5',
                                         '5QC',
                                         '5QT',
                                         'R1F',
                                         '10K',
                                         'QRL',
                                         'D9Y0V',
                                         '10L',
                                         '10J',
                                         '10R',
                                         '10V',
                                         '10X',
                                         '11A',
                                         '5FE',
                                         'RHU',
                                         'R1C',
                                         '5L1',
                                         'RW1',
                                         'RHM',
                                         'RN1')
  
  orgs_buckinghamshire_oxfordshire_and_berkshire_west <<- c('5QF',
                                                            'RXQ',
                                                            '5QD',
                                                            '10Y',
                                                            '15A',
                                                            '14Y',
                                                            'QU9',
                                                            '10H',
                                                            '10M',
                                                            '10N',
                                                            '10Q',
                                                            '10W',
                                                            '11D',
                                                            'RBF',
                                                            'RNU',
                                                            'RTH',
                                                            'RHX',
                                                            '5QE',
                                                            'RHW',
                                                            'RYE')
  
  orgs_surrey_heartlands <<- c('RTK',
                               '09N',
                               '09Y',
                               '99H',
                               '92A',
                               'QXU',
                               'RA2',
                               'RXX',
                               'RTP',
                               '5P5')
  
  
  orgs_herefordshire_and_worcestershire <<- c('R1A',
                                              '5CN',
                                              '18C',
                                              'QGH',
                                              '05F',
                                              '05J',
                                              '05T',
                                              '06D',
                                              'RWP',
                                              'RWQ',
                                              '5PL',
                                              'RLQ')
  
  orgs_birmingham <<- c('RXT',
                        'RYW',
                        '5PG',
                        'RQ3',
                        'RLU',
                        '5MX',
                        'RR1',
                        '15E',
                        'QHL',
                        '13P',
                        '04X',
                        '05P',
                        'RRJ',
                        'RXK',
                        'TAM',
                        '5QW',
                        '5M1',
                        'RRK')
  
  orgs_derbyshire <<- c('RFS',
                        '5N7',
                        'RY8',
                        '5N6',
                        'RXM',
                        '15M',
                        'QJ2',
                        '03X',
                        '03Y',
                        '04J',
                        '04R',
                        'RTG')
  
  orgs_lincolnshire <<- c('RY5',
                          'RP7',
                          '5N9',
                          '71E',
                          '03T',
                          'QJM',
                          '04D',
                          '99D',
                          '04Q',
                          'RWD')
  
  orgs_leicestershire_and_rutland <<- c('5PC',
                                        '5PA',
                                        'RT5',
                                        '03W',
                                        '04C',
                                        'QK1',
                                        '04V',
                                        'RWE')
  
  orgs_staffordshire_and_stoke_on_trent <<- c('RJF',
                                              'RJD',
                                              'RRE',
                                              '04Y',
                                              '05D',
                                              '05G',
                                              '05Q',
                                              '05V',
                                              'QNC',
                                              '05W',
                                              'RLY',
                                              '5PH',
                                              '5PK',
                                              'R1E',
                                              '5PJ',
                                              'RJE')
  
  orgs_shropshire_telford_and_wrekin <<- c('05N',
                                           'M2L0M',
                                           'QOC',
                                           '05X',
                                           'RL1',
                                           'RXW',
                                           'R1D',
                                           '5M2',
                                           '5MK')
  
  orgs_northamptonshire <<- c('RNQ',
                              '03V',
                              '04G',
                              '78H',
                              'QPM',
                              'RNS',
                              'RP1',
                              '5PD')
  
  orgs_nottinghamshire <<- c('5ET',
                             'RX9',
                             '02Q',
                             '04E',
                             '04H',
                             '52R',
                             'QT1',
                             '04K',
                             '04L',
                             '04M',
                             '04N',
                             '5EM',
                             'RX1',
                             '5N8',
                             'RHA',
                             'RK5')
  
  orgs_black_country <<- c('TAJ',
                           'RYK-X',
                           'RNA',
                           'RYK',
                           '5PE',
                           'D2P2L',
                           'QUA',
                           '05C',
                           '05L',
                           '05Y',
                           '06A',
                           'RL4',
                           '5PF',
                           'RBK',
                           '5M3',
                           'RYA',
                           '5MV')
  
  orgs_coventry_and_warwickshire <<- c('RYG',
                                       '5MD',
                                       'RLT',
                                       '05A',
                                       'B2M3M',
                                       'QWU',
                                       '05R',
                                       '05H',
                                       'RJC',
                                       'RKB',
                                       '5PM')
  
  
  
  
  orgs_mid_and_south_essex <<- c('RDD',
                                 'R1L',
                                 'RAJ',
                                 'RQ8',
                                 '5PX',
                                 '99E',
                                 '99F',
                                 'QH8',
                                 '06Q',
                                 '99G',
                                 '07G',
                                 '5P1',
                                 'RWN',
                                 '5PY')
  
  orgs_bedfordshire_luton_and_milton_keynes <<- c('RC1',
                                                  'RV7',
                                                  'RC9',
                                                  '5P2',
                                                  '5GC',
                                                  '5CQ',
                                                  'RD8',
                                                  '06F',
                                                  'M1J4Y',
                                                  'QHG',
                                                  '06P',
                                                  '04F')
  
  orgs_suffolk_and_north_east_essex <<-c('RDE',
                                         'RGQ',
                                         '06T',
                                         'QJG',
                                         '07K',
                                         '5PW',
                                         'RRD',
                                         'RT6',
                                         '5PT',
                                         'RGR')
  
  orgs_hertfordshire_and_west_essex <<- c('RWH',
                                          '5P3',
                                          'RY4',
                                          'RWR',
                                          '5QV',
                                          '06K',
                                          'QM7',
                                          '06N',
                                          '07H',
                                          'RQW',
                                          '5PV',
                                          '5P4',
                                          'RWG')
  
  orgs_norfolk_and_waveney <<- c('5PR',
                                 'RGP',
                                 '06M',
                                 '26A',
                                 'QMM',
                                 '06V',
                                 '06W',
                                 '06Y',
                                 '07J',
                                 'RM1',
                                 'RMY',
                                 'RY3',
                                 '5PQ',
                                 'RCX')
  
  orgs_cambridgeshire_and_peterborough <<- c('RGT',
                                             'RT1',
                                             'RYV',
                                             '5PP',
                                             'RYC',
                                             'RQQ',
                                             '06H',
                                             'QUE',
                                             'RGN',
                                             '5PN',
                                             'RGM')
  
  
  orgs_lancashire_and_south_cumbria <<- c('5CC',
                                          'TAP',
                                          '5HP',
                                          'RXL',
                                          'RJX',
                                          '5NG',
                                          'RXR',
                                          '5NH',
                                          'RW5',
                                          'RXN',
                                          '00Q',
                                          '00R',
                                          '00X',
                                          '01A',
                                          '02M',
                                          '01E',
                                          'QE1',
                                          '01K',
                                          '02G',
                                          '5NF',
                                          'RTX')
  
  
  orgs_greater_manchester <<- c('5HG',
                                'RMC',
                                '5HQ',
                                '5JX',
                                'RW3',
                                'RBV',
                                'RXV',
                                '5NQ',
                                'TAE',
                                '5NT',
                                'R0A',
                                '00T',
                                '00V',
                                '00W',
                                'QOP',
                                '01D',
                                '14L',
                                '01M',
                                '00Y',
                                '01G',
                                '01N',
                                '01W',
                                '01Y',
                                '02A',
                                '02H',
                                'RX7',
                                'RM3',
                                '5J5',
                                'RW6',
                                'RT2',
                                '5F5',
                                'RWJ',
                                '5F7',
                                'RMP',
                                '5LH',
                                'RM4',
                                '5NR',
                                'RM2',
                                'RRF')
  
  orgs_cheshire_and_merseyside <<-c('RBS',
                                    'RY2',
                                    '5NP',
                                    'RXA',
                                    'REN',
                                    'RJR',
                                    'RJN',
                                    '5NM',
                                    '5J4',
                                    'RY1',
                                    'RBQ',
                                    '5NL',
                                    'REM',
                                    'REP',
                                    'RBN',
                                    'RW4',
                                    'RBT',
                                    'QYG',
                                    '27D',
                                    '01C',
                                    '01F',
                                    '01J',
                                    '99A',
                                    '01R',
                                    '01T',
                                    '01X',
                                    '02D',
                                    '02E',
                                    '02F',
                                    '12F',
                                    'RTV',
                                    'RQ6',
                                    '5NJ',
                                    'RVY',
                                    'RET',
                                    'RWW',
                                    '5J2',
                                    '5NN',
                                    'RY7',
                                    '5NK',
                                    'RBL')
  
  
  orgs_south_yorkshire <<-c('RFF',
                            '5JE',
                            'RP5',
                            '5N5',
                            '02P',
                            '02X',
                            '03L',
                            '03N',
                            'QF7',
                            'RXE',
                            'RFR',
                            '5H8',
                            'RCU',
                            'TAH',
                            '5N4',
                            'RHQ')
  
  orgs_north_east_and_north_cumbria <<- c('RLN',
                                          'RXP',
                                          '5ND',
                                          '5NE',
                                          'RX4',
                                          '5J9',
                                          'RR7',
                                          '5KF',
                                          '5D9',
                                          '5KM',
                                          '5D7',
                                          'RTD',
                                          '84H',
                                          '00C',
                                          '00D',
                                          '00F',
                                          '03D',
                                          '00G',
                                          '01H',
                                          '00J',
                                          'QHM',
                                          '99C',
                                          '00M',
                                          '00P',
                                          '16C',
                                          'RNN',
                                          'RNL',
                                          'RX6',
                                          'RVW',
                                          '5D8',
                                          'TAC',
                                          'RTF',
                                          '5QR',
                                          'RTR',
                                          'R0B',
                                          'RE9',
                                          '5KG',
                                          '5E1',
                                          '5KL',
                                          'RX3')
  
  orgs_humber_and_north_yorkshire <<- c('RLN',
                                        'RXP',
                                        '5ND',
                                        '5NE',
                                        'RX4',
                                        '5J9',
                                        'RR7',
                                        '5KF',
                                        '5D9',
                                        '5KM',
                                        '5D7',
                                        'RTD',
                                        '84H',
                                        '00C',
                                        '00D',
                                        '00F',
                                        '03D',
                                        '00G',
                                        '01H',
                                        '00J',
                                        'QHM',
                                        '99C',
                                        '00M',
                                        '00P',
                                        '16C',
                                        'RNN',
                                        'RNL',
                                        'RX6',
                                        'RVW',
                                        '5D8',
                                        'TAC',
                                        'RTF',
                                        '5QR',
                                        'RTR',
                                        'R0B',
                                        'RE9',
                                        '5KG',
                                        '5E1',
                                        '5KL',
                                        'RX3')
  
  
  orgs_west_yorkshire <<- c('RCF',
                            '5NY',
                            'TAD',
                            'RAE',
                            'RWY',
                            '5J6',
                            '5N2',
                            'RGD',
                            'RY6',
                            '5N1',
                            'RR8',
                            'RXF',
                            '02N',
                            '02W',
                            '36J',
                            '02R',
                            '02T',
                            '03A',
                            '03E',
                            'X2C4Y',
                            '15F',
                            '02V',
                            '03G',
                            '03C',
                            '03J',
                            '03R',
                            'QWO',
                            'RXG',
                            '5N3',
                            'RX8')
  
  
  
  
}

org_regions <- function () {
  orgs_region_london <<- c("RJ6",
                           "5K9",
                           "RVR",
                           "RY9",
                           "RAX",
                           "5A5",
                           "07V",
                           "08J",
                           "08R",
                           "08P",
                           "36L",
                           "QWE",
                           "08T",
                           "08X",
                           "5M6",
                           "RQY",
                           "RJ7",
                           "5M7",
                           "5LG",
                           "5K5",
                           "RYX",
                           "RQM",
                           "RC3",
                           "5HX",
                           "5H1",
                           "5K6",
                           "RAS2",
                           "5AT",
                           "5HY",
                           "RYJ",
                           "5LA",
                           "R1K",
                           "07P",
                           "09A",
                           "07W",
                           "08C",
                           "08E",
                           "08G",
                           "07Y",
                           "W2U3Z",
                           "QRV",
                           "08Y",
                           "RV8",
                           "RT3",
                           "RPY",
                           "RAN",
                           "RKL",
                           "RFW",
                           "5LC",
                           "RVL",
                           "5A9",
                           "RRP",
                           "TAF",
                           "5K7",
                           "RV3",
                           "5C1",
                           "RP4",
                           "5C9",
                           "5K8",
                           "RP6",
                           "07M",
                           "07R",
                           "07X",
                           "08D",
                           "08H",
                           "93C",
                           "QMJ",
                           "RAP",
                           "RAL",
                           "RNK",
                           "RRV",
                           "RKE",
                           "5C2",
                           "RF4",
                           "RNJ",
                           "R1H",
                           "5C3",
                           "RWK",
                           "5A4",
                           "RQX",
                           "5C5",
                           "RNH",
                           "07L",
                           "07T",
                           "08F",
                           "08M",
                           "A3A8R",
                           "QMF",
                           "08N",
                           "08V",
                           "08W",
                           "RAT",
                           "5NA",
                           "5C4",
                           "5NC",
                           "RGC",
                           "07Q",
                           "08A",
                           "TAK",
                           "5A7",
                           "5A8",
                           "RJ1",
                           "RJZ",
                           "5LD",
                           "RJ2",
                           "5LF",
                           "RRU",
                           "07N",
                           "07Q",
                           "08A",
                           "08K",
                           "08L",
                           "72Q",
                           "QKK",
                           "08Q",
                           "RPG",
                           "RV5",
                           "RYQ",
                           "5LE")
  
  orgs_region_south_west <<- c('5QN',
                               'RBD',
                               'RDY',
                               '5QM',
                               '11J',
                               'QVV',
                               'RD3',
                               'RDZ',
                               'R0D',
                               '5QJ',
                               '11H',
                               '15C',
                               'QUY',
                               '11T',
                               '12A',
                               'RVJ',
                               '5M8',
                               '5A3',
                               'RA7',
                               'RA3',
                               '5QP',
                               'RJ8',
                               'QT6',
                               '11N',
                               'REF',
                               '11X',
                               'QSL',
                               'RH5',
                               '5QL',
                               'RBA',
                               'RA4',
                               'R1J',
                               'RTQ',
                               'RTE',
                               '5QH',
                               '11M',
                               'QR1',
                               "RVN",
                               "5FL",
                               "RN3",
                               "11E",
                               "92G",
                               "QOX",
                               "12D",
                               "99N",
                               "RBB",
                               "RD1",
                               "RNZ",
                               "5K3",
                               "5QK",
                               "RWV",
                               "5QQ",
                               "RX5",
                               "15N",
                               "QJK",
                               "99P",
                               "99Q",
                               "RBZ",
                               "5F1",
                               "RH8",
                               "RYF",
                               "RA9",
                               "R1G",
                               "TAL",
                               "RK9")
  
  
  orgs_region_southeast <<- c('RTK',
                              '09N',
                              '09Y',
                              '99H',
                              '92A',
                              'QXU',
                              'RA2',
                              'RXX',
                              'RTP',
                              '5P5',
                              '5QF',
                              'RXQ',
                              '5QD',
                              '10Y',
                              '15A',
                              '14Y',
                              'QU9',
                              '10H',
                              '10M',
                              '10N',
                              '10Q',
                              '10W',
                              '11D',
                              'RBF',
                              'RNU',
                              'RTH',
                              'RHX',
                              '5QE',
                              'RHW',
                              'RYE',
                              'RN5',
                              '5QC',
                              '5QT',
                              'R1F',
                              '10K',
                              'QRL',
                              'D9Y0V',
                              '10L',
                              '10J',
                              '10R',
                              '10V',
                              '10X',
                              '11A',
                              '5FE',
                              'RHU',
                              'R1C',
                              '5L1',
                              'RW1',
                              'RHM',
                              'RN1',
                              '5LQ',
                              'RXH',
                              '5P7',
                              'RXC',
                              '5P8',
                              '09D',
                              '09G',
                              '09H',
                              '09L',
                              '97R',
                              '09F',
                              '09P',
                              '99K',
                              '09X',
                              'QNX',
                              '70F',
                              'RPC',
                              'RYD',
                              'RDR',
                              'RX2',
                              'RYR',
                              '5P6',
                              '5QG',
                              'RWX',
                              'RDU',
                              'RD7',
                              '10G',
                              '15D',
                              'D4U1Y',
                              'QNQ',
                              '99M',
                              '10T',
                              '10C',
                              '11C',
                              'RN7',
                              'RVV',
                              '5QA',
                              'RXY',
                              'RYY',
                              'RWF',
                              'RPA',
                              '5L3',
                              '09C',
                              '09E',
                              '09J',
                              '91Q',
                              'QKS',
                              '09W',
                              '10A',
                              '10D',
                              '10E',
                              '99J',
                              '5P9')
  
  
  
  
  orgs_region_midlands <<- c('RYG',
                             '5MD',
                             'RLT',
                             '05A',
                             'B2M3M',
                             'QWU',
                             '05R',
                             '05H',
                             'RJC',
                             'RKB',
                             '5PM',
                             'TAJ',
                             'RYK-X',
                             'RNA',
                             'RYK',
                             '5PE',
                             'D2P2L',
                             'QUA',
                             '05C',
                             '05L',
                             '05Y',
                             '06A',
                             'RL4',
                             '5PF',
                             'RBK',
                             '5M3',
                             'RYA',
                             '5MV',
                             '5ET',
                             'RX9',
                             '02Q',
                             '04E',
                             '04H',
                             '52R',
                             'QT1',
                             '04K',
                             '04L',
                             '04M',
                             '04N',
                             '5EM',
                             'RX1',
                             '5N8',
                             'RHA',
                             'RK5',
                             'RNQ',
                             '03V',
                             '04G',
                             '78H',
                             'QPM',
                             'RNS',
                             'RP1',
                             '5PD',
                             '05N',
                             'M2L0M',
                             'QOC',
                             '05X',
                             'RL1',
                             'RXW',
                             'R1D',
                             '5M2',
                             '5MK',
                             'RJF',
                             'RJD',
                             'RRE',
                             '04Y',
                             '05D',
                             '05G',
                             '05Q',
                             '05V',
                             'QNC',
                             '05W',
                             'RLY',
                             '5PH',
                             '5PK',
                             'R1E',
                             '5PJ',
                             'RJE',
                             '5PC',
                             '5PA',
                             'RT5',
                             '03W',
                             '04C',
                             'QK1',
                             '04V',
                             'RWE',
                             'RY5',
                             'RP7',
                             '5N9',
                             '71E',
                             '03T',
                             'QJM',
                             '04D',
                             '99D',
                             '04Q',
                             'RWD',
                             'RFS',
                             '5N7',
                             'RY8',
                             '5N6',
                             'RXM',
                             '15M',
                             'QJ2',
                             '03X',
                             '03Y',
                             '04J',
                             '04R',
                             'RTG',
                             'RXT',
                             'RYW',
                             '5PG',
                             'RQ3',
                             'RLU',
                             '5MX',
                             'RR1',
                             '15E',
                             'QHL',
                             '13P',
                             '04X',
                             '05P',
                             'RRJ',
                             'RXK',
                             'TAM',
                             '5QW',
                             '5M1',
                             'RRK',
                             'R1A',
                             '5CN',
                             '18C',
                             'QGH',
                             '05F',
                             '05J',
                             '05T',
                             '06D',
                             'RWP',
                             'RWQ',
                             '5PL',
                             'RLQ')
  
  
  orgs_region_east_england <<- c('RGT',
                                 'RT1',
                                 'RYV',
                                 '5PP',
                                 'RYC',
                                 'RQQ',
                                 '06H',
                                 'QUE',
                                 'RGN',
                                 '5PN',
                                 'RGM','5PR',
                                 'RGP',
                                 '06M',
                                 '26A',
                                 'QMM',
                                 '06V',
                                 '06W',
                                 '06Y',
                                 '07J',
                                 'RM1',
                                 'RMY',
                                 'RY3',
                                 '5PQ',
                                 'RCX',
                                 'RWH',
                                 '5P3',
                                 'RY4',
                                 'RWR',
                                 '5QV',
                                 '06K',
                                 'QM7',
                                 '06N',
                                 '07H',
                                 'RQW',
                                 '5PV',
                                 '5P4',
                                 'RWG',
                                 'RDE',
                                 'RGQ',
                                 '06T',
                                 'QJG',
                                 '07K',
                                 '5PW',
                                 'RRD',
                                 'RT6',
                                 '5PT',
                                 'RGR',
                                 'RC1',
                                 'RV7',
                                 'RC9',
                                 '5P2',
                                 '5GC',
                                 '5CQ',
                                 'RD8',
                                 '06F',
                                 'M1J4Y',
                                 'QHG',
                                 '06P',
                                 '04F',
                                 'RDD',
                                 'R1L',
                                 'RAJ',
                                 'RQ8',
                                 '5PX',
                                 '99E',
                                 '99F',
                                 'QH8',
                                 '06Q',
                                 '99G',
                                 '07G',
                                 '5P1',
                                 'RWN',
                                 '5PY')
  
  orgs_region_north_west <<- c('RBS',
                               'RY2',
                               '5NP',
                               'RXA',
                               'REN',
                               'RJR',
                               'RJN',
                               '5NM',
                               '5J4',
                               'RY1',
                               'RBQ',
                               '5NL',
                               'REM',
                               'REP',
                               'RBN',
                               'RW4',
                               'RBT',
                               'QYG',
                               '27D',
                               '01C',
                               '01F',
                               '01J',
                               '99A',
                               '01R',
                               '01T',
                               '01X',
                               '02D',
                               '02E',
                               '02F',
                               '12F',
                               'RTV',
                               'RQ6',
                               '5NJ',
                               'RVY',
                               'RET',
                               'RWW',
                               '5J2',
                               '5NN',
                               'RY7',
                               '5NK',
                               'RBL','5HG',
                               'RMC',
                               '5HQ',
                               '5JX',
                               'RW3',
                               'RBV',
                               'RXV',
                               '5NQ',
                               'TAE',
                               '5NT',
                               'R0A',
                               '00T',
                               '00V',
                               '00W',
                               'QOP',
                               '01D',
                               '14L',
                               '01M',
                               '00Y',
                               '01G',
                               '01N',
                               '01W',
                               '01Y',
                               '02A',
                               '02H',
                               'RX7',
                               'RM3',
                               '5J5',
                               'RW6',
                               'RT2',
                               '5F5',
                               'RWJ',
                               '5F7',
                               'RMP',
                               '5LH',
                               'RM4',
                               '5NR',
                               'RM2',
                               'RRF','5CC',
                               'TAP',
                               '5HP',
                               'RXL',
                               'RJX',
                               '5NG',
                               'RXR',
                               '5NH',
                               'RW5',
                               'RXN',
                               '00Q',
                               '00R',
                               '00X',
                               '01A',
                               '02M',
                               '01E',
                               'QE1',
                               '01K',
                               '02G',
                               '5NF',
                               'RTX')
  
  
  
  
  orgs_region_north_east_and_yorkshire <<- c('RCF',
                                             '5NY',
                                             'TAD',
                                             'RAE',
                                             'RWY',
                                             '5J6',
                                             '5N2',
                                             'RGD',
                                             'RY6',
                                             '5N1',
                                             'RR8',
                                             'RXF',
                                             '02N',
                                             '02W',
                                             '36J',
                                             '02R',
                                             '02T',
                                             '03A',
                                             '03E',
                                             'X2C4Y',
                                             '15F',
                                             '02V',
                                             '03G',
                                             '03C',
                                             '03J',
                                             '03R',
                                             'QWO',
                                             'RXG',
                                             '5N3',
                                             'RX8','RLN',
                                             'RXP',
                                             '5ND',
                                             '5NE',
                                             'RX4',
                                             '5J9',
                                             'RR7',
                                             '5KF',
                                             '5D9',
                                             '5KM',
                                             '5D7',
                                             'RTD',
                                             '84H',
                                             '00C',
                                             '00D',
                                             '00F',
                                             '03D',
                                             '00G',
                                             '01H',
                                             '00J',
                                             'QHM',
                                             '99C',
                                             '00M',
                                             '00P',
                                             '16C',
                                             'RNN',
                                             'RNL',
                                             'RX6',
                                             'RVW',
                                             '5D8',
                                             'TAC',
                                             'RTF',
                                             '5QR',
                                             'RTR',
                                             'R0B',
                                             'RE9',
                                             '5KG',
                                             '5E1',
                                             '5KL',
                                             'RX3','RLN',
                                             'RXP',
                                             '5ND',
                                             '5NE',
                                             'RX4',
                                             '5J9',
                                             'RR7',
                                             '5KF',
                                             '5D9',
                                             '5KM',
                                             '5D7',
                                             'RTD',
                                             '84H',
                                             '00C',
                                             '00D',
                                             '00F',
                                             '03D',
                                             '00G',
                                             '01H',
                                             '00J',
                                             'QHM',
                                             '99C',
                                             '00M',
                                             '00P',
                                             '16C',
                                             'RNN',
                                             'RNL',
                                             'RX6',
                                             'RVW',
                                             '5D8',
                                             'TAC',
                                             'RTF',
                                             '5QR',
                                             'RTR',
                                             'R0B',
                                             'RE9',
                                             '5KG',
                                             '5E1',
                                             '5KL',
                                             'RX3','RFF',
                                             '5JE',
                                             'RP5',
                                             '5N5',
                                             '02P',
                                             '02X',
                                             '03L',
                                             '03N',
                                             'QF7',
                                             'RXE',
                                             'RFR',
                                             '5H8',
                                             'RCU',
                                             'TAH',
                                             '5N4',
                                             'RHQ')
  
  
}

# New function to bring in data from excel workbook ----------------------------

setwd("C:/Users/Josh.Andrews/OneDrive - Department of Health and Social Care/Nurse Data")

library(readxl)

# Org region codes 

workforce_org_regions <- read_excel('Workforce Org Regions.xlsx')

orgs_bath_somerset_swindon_and_wiltshire <- rev(na.omit(rev(workforce_org_regions$orgs_bath_somerset_swindon_and_wiltshire)))
orgs_bedfordshire_luton_and_milton_keynes <- rev(na.omit(rev(workforce_org_regions$orgs_bedfordshire_luton_and_milton_keynes)))
orgs_birmingham <- rev(na.omit(rev(workforce_org_regions$orgs_birmingham)))
orgs_black_country <- rev(na.omit(rev(workforce_org_regions$orgs_black_country)))
orgs_bristol_north_somerset_and_south_gloucestershire <- rev(na.omit(rev(workforce_org_regions$orgs_bristol_north_somerset_and_south_gloucestershire)))
orgs_buckinghamshire_oxfordshire_and_berkshire_west <- rev(na.omit(rev(workforce_org_regions$orgs_buckinghamshire_oxfordshire_and_berkshire_west)))
orgs_cambridgeshire_and_peterborough <- rev(na.omit(rev(workforce_org_regions$orgs_cambridgeshire_and_peterborough)))
orgs_cheshire_and_merseyside <- rev(na.omit(rev(workforce_org_regions$orgs_cheshire_and_merseyside)))
orgs_coventry_and_warwickshire <- rev(na.omit(rev(workforce_org_regions$orgs_coventry_and_warwickshire)))
orgs_derbyshire <- rev(na.omit(rev(workforce_org_regions$orgs_derbyshire)))
orgs_devon <-rev(na.omit(rev(workforce_org_regions$orgs_devon)))
orgs_dorset <- rev(na.omit(rev(workforce_org_regions$orgs_dorset)))
orgs_frimley <- rev(na.omit(rev(workforce_org_regions$orgs_frimley)))
orgs_gloucestershire <- rev(na.omit(rev(workforce_org_regions$orgs_gloucestershire)))
orgs_greater_manchester <- rev(na.omit(rev(workforce_org_regions$orgs_greater_manchester)))
orgs_hampshire_and_isle_of_wight <- rev(na.omit(rev(workforce_org_regions$orgs_hampshire_and_isle_of_wight)))
orgs_herefordshire_and_worcestershire<- rev(na.omit(rev(workforce_org_regions$orgs_herefordshire_and_worcestershire)))
orgs_hertfordshire_and_west_essex <- rev(na.omit(rev(workforce_org_regions$orgs_hertfordshire_and_west_essex)))
orgs_humber_and_north_yorkshire <- rev(na.omit(rev(workforce_org_regions$orgs_humber_and_north_yorkshire)))
orgs_kent_and_medway <- rev(na.omit(rev(workforce_org_regions$orgs_kent_and_medway)))
orgs_lancashire_and_south_cumbria <- rev(na.omit(rev(workforce_org_regions$orgs_lancashire_and_south_cumbria)))
orgs_leicestershire_and_rutland <-rev(na.omit(rev(workforce_org_regions$orgs_leicestershire_and_rutland)))
orgs_lincolnshire <- rev(na.omit(rev(workforce_org_regions$orgs_lincolnshire)))
orgs_mid_and_south_essex <- rev(na.omit(rev(workforce_org_regions$orgs_mid_and_south_essex)))
orgs_norfolk_and_waveney <- rev(na.omit(rev(workforce_org_regions$orgs_norfolk_and_waveney)))
orgs_north_central_london <-rev(na.omit(rev(workforce_org_regions$orgs_north_central_london)))
orgs_north_east_and_north_cumbria <-rev(na.omit(rev(workforce_org_regions$orgs_north_east_and_north_cumbria)))
orgs_north_east_london <- rev(na.omit(rev(workforce_org_regions$orgs_north_east_london)))
orgs_north_west_london <- rev(na.omit(rev(workforce_org_regions$orgs_north_west_london)))
orgs_northamptonshire <- rev(na.omit(rev(workforce_org_regions$orgs_northamptonshire)))
orgs_nottinghamshire <- rev(na.omit(rev(workforce_org_regions$orgs_nottinghamshire)))
orgs_region_east_england <- rev(na.omit(rev(workforce_org_regions$orgs_region_east_england)))
orgs_region_london <- rev(na.omit(rev(workforce_org_regions$orgs_region_london)))
orgs_region_midlands <-rev(na.omit(rev(workforce_org_regions$orgs_region_midlands)))
orgs_region_north_east_and_yorkshire <- rev(na.omit(rev(workforce_org_regions$orgs_region_north_east_and_yorkshire)))
orgs_region_north_west <- rev(na.omit(rev(workforce_org_regions$orgs_region_north_west)))
orgs_region_south_west <- rev(na.omit(rev(workforce_org_regions$orgs_region_south_west)))
orgs_region_southeast <- rev(na.omit(rev(workforce_org_regions$orgs_region_southeast)))
orgs_shropshire_telford_and_wrekin <-rev(na.omit(rev(workforce_org_regions$orgs_shropshire_telford_and_wrekin)))
orgs_somerset <-rev(na.omit(rev(workforce_org_regions$orgs_somerset)))
orgs_south_east_london <- rev(na.omit(rev(workforce_org_regions$orgs_south_east_london)))
orgs_south_west_london <- rev(na.omit(rev(workforce_org_regions$orgs_south_west_london)))
orgs_south_yorkshire <- rev(na.omit(rev(workforce_org_regions$orgs_south_yorkshire)))
orgs_staffordshire_and_stoke_on_trent <- rev(na.omit(rev(workforce_org_regions$orgs_staffordshire_and_stoke_on_trent)))
orgs_suffolk_and_north_east_essex <- rev(na.omit(rev(workforce_org_regions$orgs_suffolk_and_north_east_essex)))
orgs_surrey_heartlands <- rev(na.omit(rev(workforce_org_regions$orgs_surrey_heartlands)))
orgs_sussex <- rev(na.omit(rev(workforce_org_regions$orgs_sussex)))
orgs_west_yorkshire <- rev(na.omit(rev(workforce_org_regions$orgs_west_yorkshire)))

# Workforce Staff codes 

workforce_staff_codes <- read_excel('Workforce Staff Codes.xlsx')

admin_estates_staff_codes <- rev(na.omit(rev(workforce_staff_codes$admin_estates_staff_codes)))
allied_health_staff_codes <- rev(na.omit(rev(workforce_staff_codes$allied_health_staff_codes)))
ambulance_staff_codes <-rev(na.omit(rev( workforce_staff_codes$ambulance_staff_codes)))
ambulance_support_staff_codes <- rev(na.omit(rev(workforce_staff_codes$ambulance_support_staff_codes)))
clinical_science_staff_codes <- rev(na.omit(rev(workforce_staff_codes$clinical_science_staff_codes)))
clinical_science_support_codes <- rev(na.omit(rev(workforce_staff_codes$clinical_science_support_codes)))
general_payments_staff_codes <- rev(na.omit(rev(workforce_staff_codes$general_payments_staff_codes)))
hca_support_codes <- rev(na.omit(rev(workforce_staff_codes$hca_support_codes)))
life_science_staff_codes <-rev(na.omit(rev(workforce_staff_codes$life_science_staff_codes)))
life_science_support_codes<- rev(na.omit(rev(workforce_staff_codes$life_science_support_codes)))
medical_staff_gp_codes <-rev(na.omit(rev(workforce_staff_codes$medical_staff_gp_codes)))
medical_staff_hospital_codes <-rev(na.omit(rev(workforce_staff_codes$medical_staff_hospital_codes)))
midwife_staff_codes <-rev(na.omit(rev(workforce_staff_codes$midwife_staff_codes)))
nurse_health_visitor_codes<- rev(na.omit(rev(workforce_staff_codes$nurse_health_visitor_codes)))
nurse_staff_codes <-rev(na.omit(rev(workforce_staff_codes$nurse_staff_codes)))
nursing_associate_codes <-rev(na.omit(rev(workforce_staff_codes$nursing_associate_codes)))
physical_science_staff_codes <-rev(na.omit(rev(workforce_staff_codes$physical_science_staff_codes)))
physical_science_support_codes<- rev(na.omit(rev(workforce_staff_codes$physical_science_support_codes)))
physiological_science_staff_codes <- rev(na.omit(rev(workforce_staff_codes$physiological_science_staff_codes)))
physiological_science_support_codes<- rev(na.omit(rev(workforce_staff_codes$physiological_science_support_codes)))
public_science_staff_codes <- rev(na.omit(rev(workforce_staff_codes$public_science_staff_codes)))
public_science_support_codes <- rev(na.omit(rev(workforce_staff_codes$public_science_support_codes)))
scientific_staff_codes <- rev(na.omit(rev(workforce_staff_codes$scientific_staff_codes)))
scientific_support_staff_codes<- rev(na.omit(rev(workforce_staff_codes$scientific_support_staff_codes)))
support_allied_staff_codes <-rev(na.omit(rev(workforce_staff_codes$support_allied_staff_codes)))
